openapi: 3.0.2
info:
  version: 1.0.0
  title: api.battlemon.com
  termsOfService: 'https://battlemon.com/terms/'
  contact:
    email: contact@example.com
    url: 'https://battlemon.com/contact'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: >
    This is an **alpha** version of Battlemon API.

externalDocs:
  description: If you find error please make pull request or issue.
  url: 'https://github.com/battlemon-project/battlemon-rest-api-specs'

tags:
  - name: Sales
    description: Operations about sales
servers:
  - url: 'https://api.battlemon.com/'
paths:
  /health_check:
    $ref: paths/health_check.yaml
  /sales:
    $ref: paths/sales.yaml
components:
#  securitySchemes:
#    main_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: 'http://example.com/api/oauth/dialog'
#          scopes:
#            'read:users': read users info
#            'write:users': modify or remove users
#    api_key:
#      type: apiKey
#      in: header
#      name: api_key
#    basic_auth:
#      type: http
#      scheme: basic
